#!/bin/sh
set -e

DOCKER_UID=`stat -c "%u" $APP_ROOT`
DOCKER_GID=`stat -c "%g" $APP_ROOT`

usermod -u $DOCKER_UID www-data
groupmod -g $DOCKER_GID www-data

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"
